### ISSUE TITLE
Change how env vars are configured

### ISSUE THREAD

**Issue by paddycarey** [rehabstudio/oneill#31]
At present, environment variables are configured within a container definition using a list of strings e.g.

```yaml
env:
  - "SOMEVAR=somevalue"
  - "SOMEOTHERVAR=someothervalue"
```

If it makes sense (I'm not totally convinced that it does, but it would make some use cases easier) then we could change this to allow accepting and handling richer data structures by accepting arbitrary yaml and loading it into a `map[string]interface{}` e.g.

```yaml
env:
  SOMELIST:
    - "some thing"
    - "some other thing"
  SOMEMAP:
    mapkey1: "mapvalue1"
    mapkey2: "mapvalue2"
    mapkey3: 3
```

Note that we don't lose the original functionality at all and can still pass regular old env vars, albeit with a slight change in syntax:

```yaml
env:
  SOMEVAR: "somevalue"
  SOMEOTHERVAR: "someothervalue"
```

When passing the variables to a container, oneill should encode the values as json strings and passing along with the key in the standard environment variable format `KEY=jsonString`
